package com.us.person;

import com.us.person.Person;
import com.us.person.Teacher;
import com.us.person.Run;
import java.util.Map;
import com.us.person.Result;
dialect "mvel";


                function void printName(String name,String desc) {

                  System.out.println("name:"+name+" desc:"+ desc);
              }

              function Result get(boolean temp){
                return new Result(temp);
              }


              rule "boy"
                  no-loop true
                  lock-on-active true
                  salience 1
                  when


                  $map : Map(!($map.Person.name.equalsIgnoreCase($map.Teacher.name)));


                then
                     ((Person)$map.Person).setName(((Teacher)$map.Teacher).name);
                     $map.put("result",new Result(false));
                       Run.test($map);

              end


