package com.us.person;

import com.us.person.Person;
import com.us.person.Teacher;
import com.us.person.RiskCheckService;
import java.util.Map;
import com.us.person.Result;
dialect "mvel";





              rule "boy"
                  no-loop true
                  lock-on-active true
                  salience 1
                  when


                  $map : Map(!($map.Person.name.equalsIgnoreCase($map.Teacher.name)));


                then
                     RiskCheckService.checkRiskIp((Person)$map.Person,(Teacher)$map.Teacher);

                end